/* tslint:disable */
/* eslint-disable */
/**
 * sched admin API
 * REST control-plane of the sched scheduler (daemon `--admin-port`, mounted at `/api/_*` by default). Plain HTTP + JSON, Bearer auth when `SCHED_ADMIN_KEY` is set (unset → open, dev mode). Contract lives in `docs/content/docs/09.admin-api.md`; generate a client in any language from this spec (`openapi-generator`, `kiota`, …).
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ArtifactRef {
    'name': string;
    'kind': ArtifactRefKindEnum;
    'ref'?: string;
    'url'?: string;
}

export const ArtifactRefKindEnum = {
    S3: 's3',
    Url: 'url',
    File: 'file',
    Email: 'email',
} as const;

export type ArtifactRefKindEnum = typeof ArtifactRefKindEnum[keyof typeof ArtifactRefKindEnum];

export interface CreateScheduleRequest {
    'taskName': string;
    'schedule': ScheduleEntry;
    /**
     * IANA timezone; defaults to the task\'s tz. Body-level, valid for every kind. Inner `timezone` only exists on cron entries.
     */
    'tz'?: string;
}
export interface Health200Response {
    'ok': boolean;
    'uptimeMs': number;
    'version': string;
}
export interface InlineObject {
    'task': TaskRecord;
}
export interface InlineObject1 {
    'run': RunRecord;
}
export interface InlineObject2 {
    'schedule': ScheduleRecord;
}
export interface InlineObject3 {
    'ok': boolean;
    'id'?: string;
    'name'?: string;
    'paused': boolean;
}
export interface InlineObject4 {
    'id': string;
    'taskName': string;
    'runner': string;
    'status': RunStatus;
    'data'?: any;
    'result'?: any;
    'error'?: string;
    'progress'?: number;
    'log'?: string;
    'artifacts'?: Array<ArtifactRef>;
    'workerRef'?: string;
    'attempt': number;
    'trigger': RunTrigger;
    'triggeredBy'?: string;
    'scheduleId'?: string;
    'temporary': boolean;
    'retryOf'?: string;
    'startedAt': string;
    'finishedAt'?: string;
    /**
     * tail of the log from logFromOffset
     */
    'logChunk'?: string;
    /**
     * total log length
     */
    'logTotalLength'?: number;
}


export interface ListRuns200Response {
    'runs': Array<RunRecord>;
}
export interface ListSchedules200Response {
    'schedules': Array<ScheduleRecord>;
}
export interface ListTasks200Response {
    'tasks': Array<TaskRecord>;
}
export interface ModelError {
    'error': string;
}
/**
 * partial merge (RFC 7396): only given fields change; re-targeting a schedule to another task is a delete+create, NOT a patch
 */
export interface PatchScheduleBody {
    'schedule'?: ScheduleEntry;
    'tz'?: string;
}
export interface RetryPolicy {
    'maxAttempts': number;
    'backoffMs': number;
    'multiplier'?: number;
}
export interface RunRecord {
    'id': string;
    'taskName': string;
    'runner': string;
    'status': RunStatus;
    'data'?: any;
    'result'?: any;
    'error'?: string | null;
    'progress'?: number | null;
    'log'?: string | null;
    'artifacts'?: Array<ArtifactRef> | null;
    'workerRef'?: string | null;
    'attempt': number;
    'trigger': RunTrigger;
    'triggeredBy'?: string | null;
    'scheduleId'?: string | null;
    'temporary': boolean;
    'retryOf'?: string | null;
    'startedAt': string;
    'finishedAt'?: string | null;
}



export const RunStatus = {
    Queued: 'queued',
    Running: 'running',
    Succeeded: 'succeeded',
    Failed: 'failed',
    Cancelled: 'cancelled',
} as const;

export type RunStatus = typeof RunStatus[keyof typeof RunStatus];



export const RunTrigger = {
    Schedule: 'schedule',
    Manual: 'manual',
} as const;

export type RunTrigger = typeof RunTrigger[keyof typeof RunTrigger];


/**
 * Normalized firing rule as stored/reported (output form): cron keeps {kind,cron,timezone?}; interval normalizes to {kind,ms}; once normalizes to {kind,at}. Flat (no oneOf/discriminator) for generator compatibility — per-kind shape is enforced server-side by parseScheduleEntry.
 */
export interface Schedule {
    'kind': ScheduleKindEnum;
    /**
     * 5/6-field cron expression (kind=cron)
     */
    'cron'?: string;
    /**
     * inner timezone, valid only on cron entries
     */
    'timezone'?: string;
    /**
     * interval period in milliseconds (kind=interval)
     */
    'ms'?: number;
    /**
     * one-shot ISO instant (kind=once)
     */
    'at'?: string;
}

export const ScheduleKindEnum = {
    Cron: 'cron',
    Interval: 'interval',
    Once: 'once',
} as const;

export type ScheduleKindEnum = typeof ScheduleKindEnum[keyof typeof ScheduleKindEnum];

/**
 * one tasks.json-style firing rule: cron | interval | once + optional tenant fields
 */
export interface ScheduleEntry {
    'cron'?: string;
    /**
     * human interval, e.g. \'every 5 minutes\'
     */
    'interval'?: string;
    /**
     * date expression, e.g. \'2026-08-19T12:00:00Z\'
     */
    'once'?: string;
    /**
     * inner timezone — cron only
     */
    'timezone'?: string;
    'data'?: any;
    'externalId'?: string;
    'dedupKey'?: string;
    'retry'?: RetryPolicy;
    'priority'?: number;
}
export interface ScheduleRecord {
    'id': string;
    'taskName': string;
    'schedule': Schedule;
    'tz': string;
    'data'?: any;
    'externalId'?: string | null;
    'dedupKey'?: string | null;
    'nextRunAt'?: string | null;
    'lastRunAt'?: string | null;
    'lockedAt'?: string | null;
    'failCount'?: number;
    'priority'?: number;
    'retry'?: RetryPolicy | null;
    'retryCount'?: number;
    'lastRunId'?: string | null;
    'paused'?: boolean;
    'disabled'?: boolean;
    'fileManaged'?: boolean;
    /**
     * how the last run ended (list + single GET)
     */
    'lastRunStatus'?: RunStatus | null;
    /**
     * AND-semantics pause: paused-task (task holds the family) / paused-schedule / active
     */
    'effectiveStatus'?: ScheduleRecordEffectiveStatusEnum | null;
}

export const ScheduleRecordEffectiveStatusEnum = {
    Active: 'active',
    PausedSchedule: 'paused-schedule',
    PausedTask: 'paused-task',
} as const;

export type ScheduleRecordEffectiveStatusEnum = typeof ScheduleRecordEffectiveStatusEnum[keyof typeof ScheduleRecordEffectiveStatusEnum];

/**
 * runtime task body — same shape as one tasks.json task
 */
export interface TaskDefinition {
    'name': string;
    'runner': string;
    'schedule'?: ScheduleEntry;
    'tz'?: string;
    'config'?: object;
    'label'?: string;
    'description'?: string;
    'retry'?: RetryPolicy;
    'priority'?: number;
    'data'?: any;
    'allowedTools'?: Array<any>;
}
export interface TaskRecord {
    'name': string;
    'runner': string;
    'schedule': Schedule | null;
    'tz': string;
    'config': object;
    'label'?: string | null;
    'description'?: string | null;
    'nextRunAt'?: string | null;
    'lastRunAt'?: string | null;
    'lockedAt'?: string | null;
    'failCount'?: number;
    'priority'?: number;
    'retry'?: RetryPolicy | null;
    'retryCount'?: number;
    'lastRunId'?: string | null;
    /**
     * true/absent = tasks.json-managed; false = runtime
     */
    'fileManaged'?: boolean;
    'paused'?: boolean;
    'disabled'?: boolean;
    /**
     * how the last run ended — present on list responses
     */
    'lastRunStatus'?: RunStatus | null;
}


export interface TriggerTaskRequest {
    /**
     * short retention class (24h default)
     */
    'temporary'?: boolean;
    'data'?: any;
}

/**
 * HealthApi - axios parameter creator
 */
export const HealthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Liveness + version
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        health: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 */
export const HealthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Liveness + version
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async health(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Health200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.health(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HealthApi.health']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HealthApi - factory interface
 */
export const HealthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HealthApiFp(configuration)
    return {
        /**
         * 
         * @summary Liveness + version
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        health(options?: RawAxiosRequestConfig): AxiosPromise<Health200Response> {
            return localVarFp.health(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HealthApi - object-oriented interface
 */
export class HealthApi extends BaseAPI {
    /**
     * 
     * @summary Liveness + version
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public health(options?: RawAxiosRequestConfig) {
        return HealthApiFp(this.configuration).health(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * RunsApi - axios parameter creator
 */
export const RunsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Cancel an in-flight run (AbortSignal to the runner)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelRun: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cancelRun', 'id', id)
            const localVarPath = `/runs/{id}/cancel`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a run (terminal runs only; active runs must be cancelled first — 409)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRun: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteRun', 'id', id)
            const localVarPath = `/runs/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get one run (log snapshot; `logFromOffset` → incremental chunk)
         * @param {string} id 
         * @param {number} [logFromOffset] Return logChunk from this char offset + logTotalLength instead of the full log
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRun: async (id: string, logFromOffset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getRun', 'id', id)
            const localVarPath = `/runs/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (logFromOffset !== undefined) {
                localVarQueryParameter['logFromOffset'] = logFromOffset;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Proxy one stored artifact (s3 kind) so the bucket stays private
         * @param {string} id 
         * @param {number} idx 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRunArtifact: async (id: string, idx: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getRunArtifact', 'id', id)
            // verify required parameter 'idx' is not null or undefined
            assertParamExists('getRunArtifact', 'idx', idx)
            const localVarPath = `/runs/{id}/artifacts/{idx}`
                .replace('{id}', encodeURIComponent(String(id)))
                .replace('{idx}', encodeURIComponent(String(idx)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/octet-stream,application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List runs (DESC by startedAt, cap 1000)
         * @param {string} [task] Filter by task name
         * @param {RunStatus} [status] Filter by run status
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRuns: async (task?: string, status?: RunStatus, limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/runs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (task !== undefined) {
                localVarQueryParameter['task'] = task;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retry a finished run (new run, same retention class)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retryRun: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('retryRun', 'id', id)
            const localVarPath = `/runs/{id}/retry`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RunsApi - functional programming interface
 */
export const RunsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RunsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Cancel an in-flight run (AbortSignal to the runner)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelRun(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineObject1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelRun(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RunsApi.cancelRun']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a run (terminal runs only; active runs must be cancelled first — 409)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteRun(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteRun(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RunsApi.deleteRun']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get one run (log snapshot; `logFromOffset` → incremental chunk)
         * @param {string} id 
         * @param {number} [logFromOffset] Return logChunk from this char offset + logTotalLength instead of the full log
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRun(id: string, logFromOffset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineObject4>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRun(id, logFromOffset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RunsApi.getRun']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Proxy one stored artifact (s3 kind) so the bucket stays private
         * @param {string} id 
         * @param {number} idx 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRunArtifact(id: string, idx: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRunArtifact(id, idx, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RunsApi.getRunArtifact']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List runs (DESC by startedAt, cap 1000)
         * @param {string} [task] Filter by task name
         * @param {RunStatus} [status] Filter by run status
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listRuns(task?: string, status?: RunStatus, limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListRuns200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listRuns(task, status, limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RunsApi.listRuns']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retry a finished run (new run, same retention class)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retryRun(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineObject1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retryRun(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RunsApi.retryRun']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RunsApi - factory interface
 */
export const RunsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RunsApiFp(configuration)
    return {
        /**
         * 
         * @summary Cancel an in-flight run (AbortSignal to the runner)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelRun(id: string, options?: RawAxiosRequestConfig): AxiosPromise<InlineObject1> {
            return localVarFp.cancelRun(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a run (terminal runs only; active runs must be cancelled first — 409)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRun(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteRun(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get one run (log snapshot; `logFromOffset` → incremental chunk)
         * @param {string} id 
         * @param {number} [logFromOffset] Return logChunk from this char offset + logTotalLength instead of the full log
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRun(id: string, logFromOffset?: number, options?: RawAxiosRequestConfig): AxiosPromise<InlineObject4> {
            return localVarFp.getRun(id, logFromOffset, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Proxy one stored artifact (s3 kind) so the bucket stays private
         * @param {string} id 
         * @param {number} idx 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRunArtifact(id: string, idx: number, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.getRunArtifact(id, idx, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List runs (DESC by startedAt, cap 1000)
         * @param {string} [task] Filter by task name
         * @param {RunStatus} [status] Filter by run status
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRuns(task?: string, status?: RunStatus, limit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<ListRuns200Response> {
            return localVarFp.listRuns(task, status, limit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retry a finished run (new run, same retention class)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retryRun(id: string, options?: RawAxiosRequestConfig): AxiosPromise<InlineObject1> {
            return localVarFp.retryRun(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RunsApi - object-oriented interface
 */
export class RunsApi extends BaseAPI {
    /**
     * 
     * @summary Cancel an in-flight run (AbortSignal to the runner)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cancelRun(id: string, options?: RawAxiosRequestConfig) {
        return RunsApiFp(this.configuration).cancelRun(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a run (terminal runs only; active runs must be cancelled first — 409)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteRun(id: string, options?: RawAxiosRequestConfig) {
        return RunsApiFp(this.configuration).deleteRun(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get one run (log snapshot; `logFromOffset` → incremental chunk)
     * @param {string} id 
     * @param {number} [logFromOffset] Return logChunk from this char offset + logTotalLength instead of the full log
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRun(id: string, logFromOffset?: number, options?: RawAxiosRequestConfig) {
        return RunsApiFp(this.configuration).getRun(id, logFromOffset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Proxy one stored artifact (s3 kind) so the bucket stays private
     * @param {string} id 
     * @param {number} idx 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRunArtifact(id: string, idx: number, options?: RawAxiosRequestConfig) {
        return RunsApiFp(this.configuration).getRunArtifact(id, idx, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List runs (DESC by startedAt, cap 1000)
     * @param {string} [task] Filter by task name
     * @param {RunStatus} [status] Filter by run status
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listRuns(task?: string, status?: RunStatus, limit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return RunsApiFp(this.configuration).listRuns(task, status, limit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retry a finished run (new run, same retention class)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public retryRun(id: string, options?: RawAxiosRequestConfig) {
        return RunsApiFp(this.configuration).retryRun(id, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SchedulesApi - axios parameter creator
 */
export const SchedulesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create or upsert a schedule (dedupKey → update, id preserved)
         * @param {CreateScheduleRequest} createScheduleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSchedule: async (createScheduleRequest: CreateScheduleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createScheduleRequest' is not null or undefined
            assertParamExists('createSchedule', 'createScheduleRequest', createScheduleRequest)
            const localVarPath = `/schedules`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createScheduleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a schedule (runs keep their history — audit survives)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSchedule: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteSchedule', 'id', id)
            const localVarPath = `/schedules/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get one schedule
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSchedule: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSchedule', 'id', id)
            const localVarPath = `/schedules/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List schedules (first-class rows: taskName, rule, tz, data, effective pause state, last run)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSchedules: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/schedules`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Partial update (RFC 7396 merge: rule/tz/data/policy change in place, untouched fields stay; nextRunAt recomputes on rule/tz change)
         * @param {string} id 
         * @param {PatchScheduleBody} patchScheduleBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchSchedule: async (id: string, patchScheduleBody: PatchScheduleBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('patchSchedule', 'id', id)
            // verify required parameter 'patchScheduleBody' is not null or undefined
            assertParamExists('patchSchedule', 'patchScheduleBody', patchScheduleBody)
            const localVarPath = `/schedules/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchScheduleBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Pause one schedule (effective status stays 🔴 paused-task if the task holds it)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pauseSchedule: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('pauseSchedule', 'id', id)
            const localVarPath = `/schedules/{id}/pause`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Resume one schedule
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resumeSchedule: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('resumeSchedule', 'id', id)
            const localVarPath = `/schedules/{id}/resume`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SchedulesApi - functional programming interface
 */
export const SchedulesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SchedulesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create or upsert a schedule (dedupKey → update, id preserved)
         * @param {CreateScheduleRequest} createScheduleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSchedule(createScheduleRequest: CreateScheduleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineObject2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSchedule(createScheduleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchedulesApi.createSchedule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a schedule (runs keep their history — audit survives)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSchedule(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSchedule(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchedulesApi.deleteSchedule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get one schedule
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSchedule(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ScheduleRecord>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSchedule(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchedulesApi.getSchedule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List schedules (first-class rows: taskName, rule, tz, data, effective pause state, last run)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSchedules(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListSchedules200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSchedules(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchedulesApi.listSchedules']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Partial update (RFC 7396 merge: rule/tz/data/policy change in place, untouched fields stay; nextRunAt recomputes on rule/tz change)
         * @param {string} id 
         * @param {PatchScheduleBody} patchScheduleBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchSchedule(id: string, patchScheduleBody: PatchScheduleBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineObject2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.patchSchedule(id, patchScheduleBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchedulesApi.patchSchedule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Pause one schedule (effective status stays 🔴 paused-task if the task holds it)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pauseSchedule(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineObject3>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pauseSchedule(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchedulesApi.pauseSchedule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Resume one schedule
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resumeSchedule(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineObject3>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resumeSchedule(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchedulesApi.resumeSchedule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SchedulesApi - factory interface
 */
export const SchedulesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SchedulesApiFp(configuration)
    return {
        /**
         * 
         * @summary Create or upsert a schedule (dedupKey → update, id preserved)
         * @param {CreateScheduleRequest} createScheduleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSchedule(createScheduleRequest: CreateScheduleRequest, options?: RawAxiosRequestConfig): AxiosPromise<InlineObject2> {
            return localVarFp.createSchedule(createScheduleRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a schedule (runs keep their history — audit survives)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSchedule(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteSchedule(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get one schedule
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSchedule(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ScheduleRecord> {
            return localVarFp.getSchedule(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List schedules (first-class rows: taskName, rule, tz, data, effective pause state, last run)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSchedules(options?: RawAxiosRequestConfig): AxiosPromise<ListSchedules200Response> {
            return localVarFp.listSchedules(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Partial update (RFC 7396 merge: rule/tz/data/policy change in place, untouched fields stay; nextRunAt recomputes on rule/tz change)
         * @param {string} id 
         * @param {PatchScheduleBody} patchScheduleBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchSchedule(id: string, patchScheduleBody: PatchScheduleBody, options?: RawAxiosRequestConfig): AxiosPromise<InlineObject2> {
            return localVarFp.patchSchedule(id, patchScheduleBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Pause one schedule (effective status stays 🔴 paused-task if the task holds it)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pauseSchedule(id: string, options?: RawAxiosRequestConfig): AxiosPromise<InlineObject3> {
            return localVarFp.pauseSchedule(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Resume one schedule
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resumeSchedule(id: string, options?: RawAxiosRequestConfig): AxiosPromise<InlineObject3> {
            return localVarFp.resumeSchedule(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SchedulesApi - object-oriented interface
 */
export class SchedulesApi extends BaseAPI {
    /**
     * 
     * @summary Create or upsert a schedule (dedupKey → update, id preserved)
     * @param {CreateScheduleRequest} createScheduleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createSchedule(createScheduleRequest: CreateScheduleRequest, options?: RawAxiosRequestConfig) {
        return SchedulesApiFp(this.configuration).createSchedule(createScheduleRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a schedule (runs keep their history — audit survives)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteSchedule(id: string, options?: RawAxiosRequestConfig) {
        return SchedulesApiFp(this.configuration).deleteSchedule(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get one schedule
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSchedule(id: string, options?: RawAxiosRequestConfig) {
        return SchedulesApiFp(this.configuration).getSchedule(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List schedules (first-class rows: taskName, rule, tz, data, effective pause state, last run)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listSchedules(options?: RawAxiosRequestConfig) {
        return SchedulesApiFp(this.configuration).listSchedules(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Partial update (RFC 7396 merge: rule/tz/data/policy change in place, untouched fields stay; nextRunAt recomputes on rule/tz change)
     * @param {string} id 
     * @param {PatchScheduleBody} patchScheduleBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public patchSchedule(id: string, patchScheduleBody: PatchScheduleBody, options?: RawAxiosRequestConfig) {
        return SchedulesApiFp(this.configuration).patchSchedule(id, patchScheduleBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Pause one schedule (effective status stays 🔴 paused-task if the task holds it)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public pauseSchedule(id: string, options?: RawAxiosRequestConfig) {
        return SchedulesApiFp(this.configuration).pauseSchedule(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Resume one schedule
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public resumeSchedule(id: string, options?: RawAxiosRequestConfig) {
        return SchedulesApiFp(this.configuration).resumeSchedule(id, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TasksApi - axios parameter creator
 */
export const TasksApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete a task (runs keep their history)
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTask: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('deleteTask', 'name', name)
            const localVarPath = `/tasks/{name}`
                .replace('{name}', encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get one task
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTask: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('getTask', 'name', name)
            const localVarPath = `/tasks/{name}`
                .replace('{name}', encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List tasks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTasks: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/tasks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Pause a task (family stop — all its schedules hold)
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pauseTask: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('pauseTask', 'name', name)
            const localVarPath = `/tasks/{name}/pause`
                .replace('{name}', encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Resume a paused task
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resumeTask: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('resumeTask', 'name', name)
            const localVarPath = `/tasks/{name}/resume`
                .replace('{name}', encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Trigger a manual run (optional { temporary?, data? })
         * @param {string} name 
         * @param {TriggerTaskRequest} [triggerTaskRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        triggerTask: async (name: string, triggerTaskRequest?: TriggerTaskRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('triggerTask', 'name', name)
            const localVarPath = `/tasks/{name}/run`
                .replace('{name}', encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(triggerTaskRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register/upsert a runtime task (validated exactly like tasks.json)
         * @param {TaskDefinition} taskDefinition 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upsertTask: async (taskDefinition: TaskDefinition, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'taskDefinition' is not null or undefined
            assertParamExists('upsertTask', 'taskDefinition', taskDefinition)
            const localVarPath = `/tasks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(taskDefinition, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TasksApi - functional programming interface
 */
export const TasksApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TasksApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Delete a task (runs keep their history)
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTask(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTask(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.deleteTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get one task
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTask(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskRecord>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTask(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.getTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List tasks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTasks(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListTasks200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTasks(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.listTasks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Pause a task (family stop — all its schedules hold)
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pauseTask(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineObject3>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pauseTask(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.pauseTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Resume a paused task
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resumeTask(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineObject3>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resumeTask(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.resumeTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Trigger a manual run (optional { temporary?, data? })
         * @param {string} name 
         * @param {TriggerTaskRequest} [triggerTaskRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async triggerTask(name: string, triggerTaskRequest?: TriggerTaskRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineObject1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.triggerTask(name, triggerTaskRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.triggerTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Register/upsert a runtime task (validated exactly like tasks.json)
         * @param {TaskDefinition} taskDefinition 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async upsertTask(taskDefinition: TaskDefinition, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineObject>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.upsertTask(taskDefinition, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.upsertTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TasksApi - factory interface
 */
export const TasksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TasksApiFp(configuration)
    return {
        /**
         * 
         * @summary Delete a task (runs keep their history)
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTask(name: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteTask(name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get one task
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTask(name: string, options?: RawAxiosRequestConfig): AxiosPromise<TaskRecord> {
            return localVarFp.getTask(name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List tasks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTasks(options?: RawAxiosRequestConfig): AxiosPromise<ListTasks200Response> {
            return localVarFp.listTasks(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Pause a task (family stop — all its schedules hold)
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pauseTask(name: string, options?: RawAxiosRequestConfig): AxiosPromise<InlineObject3> {
            return localVarFp.pauseTask(name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Resume a paused task
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resumeTask(name: string, options?: RawAxiosRequestConfig): AxiosPromise<InlineObject3> {
            return localVarFp.resumeTask(name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Trigger a manual run (optional { temporary?, data? })
         * @param {string} name 
         * @param {TriggerTaskRequest} [triggerTaskRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        triggerTask(name: string, triggerTaskRequest?: TriggerTaskRequest, options?: RawAxiosRequestConfig): AxiosPromise<InlineObject1> {
            return localVarFp.triggerTask(name, triggerTaskRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register/upsert a runtime task (validated exactly like tasks.json)
         * @param {TaskDefinition} taskDefinition 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upsertTask(taskDefinition: TaskDefinition, options?: RawAxiosRequestConfig): AxiosPromise<InlineObject> {
            return localVarFp.upsertTask(taskDefinition, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TasksApi - object-oriented interface
 */
export class TasksApi extends BaseAPI {
    /**
     * 
     * @summary Delete a task (runs keep their history)
     * @param {string} name 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteTask(name: string, options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).deleteTask(name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get one task
     * @param {string} name 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTask(name: string, options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).getTask(name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List tasks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listTasks(options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).listTasks(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Pause a task (family stop — all its schedules hold)
     * @param {string} name 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public pauseTask(name: string, options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).pauseTask(name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Resume a paused task
     * @param {string} name 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public resumeTask(name: string, options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).resumeTask(name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Trigger a manual run (optional { temporary?, data? })
     * @param {string} name 
     * @param {TriggerTaskRequest} [triggerTaskRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public triggerTask(name: string, triggerTaskRequest?: TriggerTaskRequest, options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).triggerTask(name, triggerTaskRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register/upsert a runtime task (validated exactly like tasks.json)
     * @param {TaskDefinition} taskDefinition 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public upsertTask(taskDefinition: TaskDefinition, options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).upsertTask(taskDefinition, options).then((request) => request(this.axios, this.basePath));
    }
}



