/* tslint:disable */
/* eslint-disable */
/**
 * sched admin API
 * REST control-plane of the sched scheduler (daemon `--admin-port`, mounted at `/api/_*` by default). Plain HTTP + JSON, Bearer auth when `SCHED_ADMIN_KEY` is set (unset → open, dev mode). Contract lives in `docs/content/docs/09.admin-api.md`; generate a client in any language from this spec (`openapi-generator`, `kiota`, …).
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

