# coding: utf-8

# flake8: noqa
"""
    sched admin API

    REST control-plane of the sched scheduler (daemon `--admin-port`, mounted at `/api/*` by default). Plain HTTP + JSON, Bearer auth when `SCHED_ADMIN_KEY` is set (unset → open, dev mode). Contract lives in `docs/content/docs/09.admin-api.md`; generate a client in any language from this spec (`openapi-generator`, `kiota`, …).

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from sched_admin_client.models.artifact_ref import ArtifactRef
from sched_admin_client.models.create_schedule_request import CreateScheduleRequest
from sched_admin_client.models.error import Error
from sched_admin_client.models.health200_response import Health200Response
from sched_admin_client.models.inline_object import InlineObject
from sched_admin_client.models.inline_object1 import InlineObject1
from sched_admin_client.models.inline_object2 import InlineObject2
from sched_admin_client.models.inline_object3 import InlineObject3
from sched_admin_client.models.inline_object4 import InlineObject4
from sched_admin_client.models.list_runs200_response import ListRuns200Response
from sched_admin_client.models.list_schedules200_response import ListSchedules200Response
from sched_admin_client.models.list_tasks200_response import ListTasks200Response
from sched_admin_client.models.patch_schedule_body import PatchScheduleBody
from sched_admin_client.models.retry_policy import RetryPolicy
from sched_admin_client.models.run_record import RunRecord
from sched_admin_client.models.run_status import RunStatus
from sched_admin_client.models.run_trigger import RunTrigger
from sched_admin_client.models.schedule import Schedule
from sched_admin_client.models.schedule_entry import ScheduleEntry
from sched_admin_client.models.schedule_record import ScheduleRecord
from sched_admin_client.models.task_definition import TaskDefinition
from sched_admin_client.models.task_record import TaskRecord
from sched_admin_client.models.trigger_task_request import TriggerTaskRequest

