# coding: utf-8

"""
    sched admin API

    REST control-plane of the sched scheduler (daemon `--admin-port`, mounted at `/api/*` by default). Plain HTTP + JSON, Bearer auth when `SCHED_ADMIN_KEY` is set (unset → open, dev mode). Contract lives in `docs/content/docs/09.admin-api.md`; generate a client in any language from this spec (`openapi-generator`, `kiota`, …).

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RunTrigger(str, Enum):
    """
    RunTrigger
    """

    """
    allowed enum values
    """
    SCHEDULE = 'schedule'
    MANUAL = 'manual'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RunTrigger from a JSON string"""
        return cls(json.loads(json_str))


