# coding: utf-8

"""
    sched admin API

    REST control-plane of the sched scheduler (daemon `--admin-port`, mounted at `/api/*` by default). Plain HTTP + JSON, Bearer auth when `SCHED_ADMIN_KEY` is set (unset → open, dev mode). Contract lives in `docs/content/docs/09.admin-api.md`; generate a client in any language from this spec (`openapi-generator`, `kiota`, …).

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from sched_admin_client.models.artifact_ref import ArtifactRef
from sched_admin_client.models.run_status import RunStatus
from sched_admin_client.models.run_trigger import RunTrigger
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RunRecord(BaseModel):
    """
    RunRecord
    """ # noqa: E501
    id: StrictStr
    task_name: StrictStr = Field(alias="taskName")
    runner: StrictStr
    status: RunStatus
    data: Optional[Any] = None
    result: Optional[Any] = None
    error: Optional[StrictStr] = None
    progress: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = None
    log: Optional[StrictStr] = None
    artifacts: Optional[List[ArtifactRef]] = None
    worker_ref: Optional[StrictStr] = Field(default=None, alias="workerRef")
    attempt: Annotated[int, Field(strict=True, ge=1)]
    trigger: RunTrigger
    triggered_by: Optional[StrictStr] = Field(default=None, alias="triggeredBy")
    schedule_id: Optional[StrictStr] = Field(default=None, alias="scheduleId")
    temporary: StrictBool
    retry_of: Optional[StrictStr] = Field(default=None, alias="retryOf")
    started_at: datetime = Field(alias="startedAt")
    finished_at: Optional[datetime] = Field(default=None, alias="finishedAt")
    __properties: ClassVar[List[str]] = ["id", "taskName", "runner", "status", "data", "result", "error", "progress", "log", "artifacts", "workerRef", "attempt", "trigger", "triggeredBy", "scheduleId", "temporary", "retryOf", "startedAt", "finishedAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RunRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in artifacts (list)
        _items = []
        if self.artifacts:
            for _item_artifacts in self.artifacts:
                if _item_artifacts:
                    _items.append(_item_artifacts.to_dict())
            _dict['artifacts'] = _items
        # set to None if data (nullable) is None
        # and model_fields_set contains the field
        if self.data is None and "data" in self.model_fields_set:
            _dict['data'] = None

        # set to None if result (nullable) is None
        # and model_fields_set contains the field
        if self.result is None and "result" in self.model_fields_set:
            _dict['result'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if progress (nullable) is None
        # and model_fields_set contains the field
        if self.progress is None and "progress" in self.model_fields_set:
            _dict['progress'] = None

        # set to None if log (nullable) is None
        # and model_fields_set contains the field
        if self.log is None and "log" in self.model_fields_set:
            _dict['log'] = None

        # set to None if artifacts (nullable) is None
        # and model_fields_set contains the field
        if self.artifacts is None and "artifacts" in self.model_fields_set:
            _dict['artifacts'] = None

        # set to None if worker_ref (nullable) is None
        # and model_fields_set contains the field
        if self.worker_ref is None and "worker_ref" in self.model_fields_set:
            _dict['workerRef'] = None

        # set to None if triggered_by (nullable) is None
        # and model_fields_set contains the field
        if self.triggered_by is None and "triggered_by" in self.model_fields_set:
            _dict['triggeredBy'] = None

        # set to None if schedule_id (nullable) is None
        # and model_fields_set contains the field
        if self.schedule_id is None and "schedule_id" in self.model_fields_set:
            _dict['scheduleId'] = None

        # set to None if retry_of (nullable) is None
        # and model_fields_set contains the field
        if self.retry_of is None and "retry_of" in self.model_fields_set:
            _dict['retryOf'] = None

        # set to None if finished_at (nullable) is None
        # and model_fields_set contains the field
        if self.finished_at is None and "finished_at" in self.model_fields_set:
            _dict['finishedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RunRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "taskName": obj.get("taskName"),
            "runner": obj.get("runner"),
            "status": obj.get("status"),
            "data": obj.get("data"),
            "result": obj.get("result"),
            "error": obj.get("error"),
            "progress": obj.get("progress"),
            "log": obj.get("log"),
            "artifacts": [ArtifactRef.from_dict(_item) for _item in obj["artifacts"]] if obj.get("artifacts") is not None else None,
            "workerRef": obj.get("workerRef"),
            "attempt": obj.get("attempt"),
            "trigger": obj.get("trigger"),
            "triggeredBy": obj.get("triggeredBy"),
            "scheduleId": obj.get("scheduleId"),
            "temporary": obj.get("temporary"),
            "retryOf": obj.get("retryOf"),
            "startedAt": obj.get("startedAt"),
            "finishedAt": obj.get("finishedAt")
        })
        return _obj


