# coding: utf-8

"""
    sched admin API

    REST control-plane of the sched scheduler (daemon `--admin-port`, mounted at `/api/*` by default). Plain HTTP + JSON, Bearer auth when `SCHED_ADMIN_KEY` is set (unset → open, dev mode). Contract lives in `docs/content/docs/09.admin-api.md`; generate a client in any language from this spec (`openapi-generator`, `kiota`, …).

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from sched_admin_client.models.retry_policy import RetryPolicy
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ScheduleEntry(BaseModel):
    """
    one tasks.json-style firing rule: cron | interval | once + optional tenant fields
    """ # noqa: E501
    cron: Optional[StrictStr] = None
    interval: Optional[StrictStr] = Field(default=None, description="human interval, e.g. 'every 5 minutes'")
    once: Optional[StrictStr] = Field(default=None, description="date expression, e.g. '2026-08-19T12:00:00Z'")
    timezone: Optional[StrictStr] = Field(default=None, description="inner timezone — cron only")
    data: Optional[Any] = None
    external_id: Optional[StrictStr] = Field(default=None, alias="externalId")
    dedup_key: Optional[StrictStr] = Field(default=None, alias="dedupKey")
    retry: Optional[RetryPolicy] = None
    priority: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    __properties: ClassVar[List[str]] = ["cron", "interval", "once", "timezone", "data", "externalId", "dedupKey", "retry", "priority"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScheduleEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of retry
        if self.retry:
            _dict['retry'] = self.retry.to_dict()
        # set to None if data (nullable) is None
        # and model_fields_set contains the field
        if self.data is None and "data" in self.model_fields_set:
            _dict['data'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScheduleEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cron": obj.get("cron"),
            "interval": obj.get("interval"),
            "once": obj.get("once"),
            "timezone": obj.get("timezone"),
            "data": obj.get("data"),
            "externalId": obj.get("externalId"),
            "dedupKey": obj.get("dedupKey"),
            "retry": RetryPolicy.from_dict(obj["retry"]) if obj.get("retry") is not None else None,
            "priority": obj.get("priority")
        })
        return _obj


