# coding: utf-8

"""
    sched admin API

    REST control-plane of the sched scheduler (daemon `--admin-port`, mounted at `/api/*` by default). Plain HTTP + JSON, Bearer auth when `SCHED_ADMIN_KEY` is set (unset → open, dev mode). Contract lives in `docs/content/docs/09.admin-api.md`; generate a client in any language from this spec (`openapi-generator`, `kiota`, …).

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Schedule(BaseModel):
    """
    Normalized firing rule as stored/reported (output form): cron keeps {kind,cron,timezone?}; interval normalizes to {kind,ms}; once normalizes to {kind,at}. Flat (no oneOf/discriminator) for generator compatibility — per-kind shape is enforced server-side by parseScheduleEntry.
    """ # noqa: E501
    kind: StrictStr
    cron: Optional[StrictStr] = Field(default=None, description="5/6-field cron expression (kind=cron)")
    timezone: Optional[StrictStr] = Field(default=None, description="inner timezone, valid only on cron entries")
    ms: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="interval period in milliseconds (kind=interval)")
    at: Optional[datetime] = Field(default=None, description="one-shot ISO instant (kind=once)")
    __properties: ClassVar[List[str]] = ["kind", "cron", "timezone", "ms", "at"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['cron', 'interval', 'once']):
            raise ValueError("must be one of enum values ('cron', 'interval', 'once')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Schedule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Schedule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "kind": obj.get("kind"),
            "cron": obj.get("cron"),
            "timezone": obj.get("timezone"),
            "ms": obj.get("ms"),
            "at": obj.get("at")
        })
        return _obj


