# coding: utf-8

"""
    sched admin API

    REST control-plane of the sched scheduler (daemon `--admin-port`, mounted at `/api/*` by default). Plain HTTP + JSON, Bearer auth when `SCHED_ADMIN_KEY` is set (unset → open, dev mode). Contract lives in `docs/content/docs/09.admin-api.md`; generate a client in any language from this spec (`openapi-generator`, `kiota`, …).

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from sched_admin_client.models.retry_policy import RetryPolicy
from sched_admin_client.models.run_status import RunStatus
from sched_admin_client.models.schedule import Schedule
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TaskRecord(BaseModel):
    """
    TaskRecord
    """ # noqa: E501
    name: StrictStr
    runner: StrictStr
    schedule: Optional[Schedule]
    tz: StrictStr
    config: Dict[str, Any]
    label: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    next_run_at: Optional[datetime] = Field(default=None, alias="nextRunAt")
    last_run_at: Optional[datetime] = Field(default=None, alias="lastRunAt")
    locked_at: Optional[datetime] = Field(default=None, alias="lockedAt")
    fail_count: Optional[StrictInt] = Field(default=None, alias="failCount")
    priority: Optional[StrictInt] = None
    retry: Optional[RetryPolicy] = None
    retry_count: Optional[StrictInt] = Field(default=None, alias="retryCount")
    last_run_id: Optional[StrictStr] = Field(default=None, alias="lastRunId")
    file_managed: Optional[StrictBool] = Field(default=None, description="true/absent = tasks.json-managed; false = runtime", alias="fileManaged")
    paused: Optional[StrictBool] = None
    disabled: Optional[StrictBool] = None
    last_run_status: Optional[RunStatus] = Field(default=None, description="how the last run ended — present on list responses", alias="lastRunStatus")
    __properties: ClassVar[List[str]] = ["name", "runner", "schedule", "tz", "config", "label", "description", "nextRunAt", "lastRunAt", "lockedAt", "failCount", "priority", "retry", "retryCount", "lastRunId", "fileManaged", "paused", "disabled", "lastRunStatus"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TaskRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of schedule
        if self.schedule:
            _dict['schedule'] = self.schedule.to_dict()
        # override the default output from pydantic by calling `to_dict()` of retry
        if self.retry:
            _dict['retry'] = self.retry.to_dict()
        # set to None if schedule (nullable) is None
        # and model_fields_set contains the field
        if self.schedule is None and "schedule" in self.model_fields_set:
            _dict['schedule'] = None

        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if next_run_at (nullable) is None
        # and model_fields_set contains the field
        if self.next_run_at is None and "next_run_at" in self.model_fields_set:
            _dict['nextRunAt'] = None

        # set to None if last_run_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_run_at is None and "last_run_at" in self.model_fields_set:
            _dict['lastRunAt'] = None

        # set to None if locked_at (nullable) is None
        # and model_fields_set contains the field
        if self.locked_at is None and "locked_at" in self.model_fields_set:
            _dict['lockedAt'] = None

        # set to None if retry (nullable) is None
        # and model_fields_set contains the field
        if self.retry is None and "retry" in self.model_fields_set:
            _dict['retry'] = None

        # set to None if last_run_id (nullable) is None
        # and model_fields_set contains the field
        if self.last_run_id is None and "last_run_id" in self.model_fields_set:
            _dict['lastRunId'] = None

        # set to None if last_run_status (nullable) is None
        # and model_fields_set contains the field
        if self.last_run_status is None and "last_run_status" in self.model_fields_set:
            _dict['lastRunStatus'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TaskRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "runner": obj.get("runner"),
            "schedule": Schedule.from_dict(obj["schedule"]) if obj.get("schedule") is not None else None,
            "tz": obj.get("tz"),
            "config": obj.get("config"),
            "label": obj.get("label"),
            "description": obj.get("description"),
            "nextRunAt": obj.get("nextRunAt"),
            "lastRunAt": obj.get("lastRunAt"),
            "lockedAt": obj.get("lockedAt"),
            "failCount": obj.get("failCount"),
            "priority": obj.get("priority"),
            "retry": RetryPolicy.from_dict(obj["retry"]) if obj.get("retry") is not None else None,
            "retryCount": obj.get("retryCount"),
            "lastRunId": obj.get("lastRunId"),
            "fileManaged": obj.get("fileManaged"),
            "paused": obj.get("paused"),
            "disabled": obj.get("disabled"),
            "lastRunStatus": obj.get("lastRunStatus")
        })
        return _obj


