# coding: utf-8

# flake8: noqa

"""
    sched admin API

    REST control-plane of the sched scheduler (daemon `--admin-port`, mounted at `/api/*` by default). Plain HTTP + JSON, Bearer auth when `SCHED_ADMIN_KEY` is set (unset → open, dev mode). Contract lives in `docs/content/docs/09.admin-api.md`; generate a client in any language from this spec (`openapi-generator`, `kiota`, …).

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "HealthApi",
    "RunsApi",
    "SchedulesApi",
    "TasksApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ArtifactRef",
    "CreateScheduleRequest",
    "Error",
    "Health200Response",
    "InlineObject",
    "InlineObject1",
    "InlineObject2",
    "InlineObject3",
    "InlineObject4",
    "ListRuns200Response",
    "ListSchedules200Response",
    "ListTasks200Response",
    "PatchScheduleBody",
    "RetryPolicy",
    "RunRecord",
    "RunStatus",
    "RunTrigger",
    "Schedule",
    "ScheduleEntry",
    "ScheduleRecord",
    "TaskDefinition",
    "TaskRecord",
    "TriggerTaskRequest",
]

# import apis into sdk package
from sched_admin_client.api.health_api import HealthApi as HealthApi
from sched_admin_client.api.runs_api import RunsApi as RunsApi
from sched_admin_client.api.schedules_api import SchedulesApi as SchedulesApi
from sched_admin_client.api.tasks_api import TasksApi as TasksApi

# import ApiClient
from sched_admin_client.api_response import ApiResponse as ApiResponse
from sched_admin_client.api_client import ApiClient as ApiClient
from sched_admin_client.configuration import Configuration as Configuration
from sched_admin_client.exceptions import OpenApiException as OpenApiException
from sched_admin_client.exceptions import ApiTypeError as ApiTypeError
from sched_admin_client.exceptions import ApiValueError as ApiValueError
from sched_admin_client.exceptions import ApiKeyError as ApiKeyError
from sched_admin_client.exceptions import ApiAttributeError as ApiAttributeError
from sched_admin_client.exceptions import ApiException as ApiException

# import models into sdk package
from sched_admin_client.models.artifact_ref import ArtifactRef as ArtifactRef
from sched_admin_client.models.create_schedule_request import CreateScheduleRequest as CreateScheduleRequest
from sched_admin_client.models.error import Error as Error
from sched_admin_client.models.health200_response import Health200Response as Health200Response
from sched_admin_client.models.inline_object import InlineObject as InlineObject
from sched_admin_client.models.inline_object1 import InlineObject1 as InlineObject1
from sched_admin_client.models.inline_object2 import InlineObject2 as InlineObject2
from sched_admin_client.models.inline_object3 import InlineObject3 as InlineObject3
from sched_admin_client.models.inline_object4 import InlineObject4 as InlineObject4
from sched_admin_client.models.list_runs200_response import ListRuns200Response as ListRuns200Response
from sched_admin_client.models.list_schedules200_response import ListSchedules200Response as ListSchedules200Response
from sched_admin_client.models.list_tasks200_response import ListTasks200Response as ListTasks200Response
from sched_admin_client.models.patch_schedule_body import PatchScheduleBody as PatchScheduleBody
from sched_admin_client.models.retry_policy import RetryPolicy as RetryPolicy
from sched_admin_client.models.run_record import RunRecord as RunRecord
from sched_admin_client.models.run_status import RunStatus as RunStatus
from sched_admin_client.models.run_trigger import RunTrigger as RunTrigger
from sched_admin_client.models.schedule import Schedule as Schedule
from sched_admin_client.models.schedule_entry import ScheduleEntry as ScheduleEntry
from sched_admin_client.models.schedule_record import ScheduleRecord as ScheduleRecord
from sched_admin_client.models.task_definition import TaskDefinition as TaskDefinition
from sched_admin_client.models.task_record import TaskRecord as TaskRecord
from sched_admin_client.models.trigger_task_request import TriggerTaskRequest as TriggerTaskRequest

